### ISSUE TITLE
可以增加个深色模式吗？

### ISSUE THREAD

**Issue by Sucgz** [aaronlinv/JuiceTimetable#51]
感谢开发者

**Comment by aaronlinv** [comment]
在我的印象中 深色模式在之前的版本中已经实现了，在 MIUI 上测试通过

**Comment by aaronlinv** [comment]
顺便提一句，如果你对项目感兴趣的话可以修改然后直接 PR 代码，如果没有安卓开发经历也没关系，我也乐意提供相关的帮助

**Comment by Sucgz** [comment]
> 在我的印象中 深色模式在之前的版本中已经实现了，在 MIUI 上测试通过

鸿蒙系统无法显示深色模式

**Comment by Sucgz** [comment]
> 顺便提一句，如果你对项目感兴趣的话可以修改然后直接 PR 代码，如果没有安卓开发经历也没关系，我也乐意提供相关的帮助

感谢大佬

**Comment by aaronlinv** [comment]
近期会更新一下这个，可以私信一下我的邮箱 aaronlinv@outlook.com，下个版本会把你加到贡献名单里

**Comment by Sucgz** [comment]
> 近期会更新一下这个，可以私信一下我的邮箱 aaronlinv@outlook.com，下个版本会把你加到贡献名单里

谢谢大佬

**Comment by aaronlinv** [comment]
目前没有收到你的邮件，因为我没有鸿蒙的设备，所以可能需要你协助测试一下

**Comment by Sucgz** [comment]
怎么协助呢

aaronlinv ***@***.***> 于2021年12月8日周三 19:32写道：

**Comment by aaronlinv** [comment]
可以联系我的邮箱
