### ISSUE TITLE
哈哈，没想到还有这个 App | Interesting discovering this app

### ISSUE THREAD

**Issue by diredocks** [aaronlinv/JuiceTimetable#54]
我另外做了一个教务系统转换 ics 文件的脚本，可以直接导入兼容的日历 App 里。
另外我有时间的话可能会考虑适配至诚的教务系统到 WakeUP 课程表，那个 APP 用的人更多，只需要负责 praser 部分就好。

助学长工作顺利！

I also made a script that converts the course schedule of the Academic Affairs System into an ICS file, which can be directly imported into compatible calendar apps.

If I have time, I may also consider adapting the Academic Affairs System to WakeUP Course Schedule, which is used by more people. I would only need to be responsible for the parser part.

I hope you keep enjoying coding!

**Comment by aaronlinv** [comment]
@diredocks  噢！你的想法更好！

写解析的话可以使用 `src/androidTest/java/com/juice/timetable/data/parse` 下的测试用例，应该可以节帮你节省一些收集课表 HTML 的时间

当然，有兴趣的话我们也可以加个好友聊一聊

祝好～
