### ISSUE TITLE
我有一个问题

### ISSUE THREAD

**Issue by j1uzhou** [aaronlinv/JuiceTimetable#55]
我是个使用者，为什么我登录的时候跟我说获取不了cookie啊，这种情况该怎么解决呢

**Comment by j1uzhou** [comment]
![Screenshot_20240309_200825_com.juice.timetable_edit_130436257632949.jpg](https://github.com/aaronlinv/JuiceTimetable/assets/162807797/a6baa0f8-9c49-4c0d-8770-86a4fe014540)

情况：

**Comment by aaronlinv** [comment]
@j1uzhou 这个问题下一个版本会修复，应该很快
感谢你的反馈，你可以提供一个你的昵称，我会把它放到关于页面的感谢列表里

**Comment by j1uzhou** [comment]
不用加我名字了，我只是一个使用者，说到底是我享受了便利的

**Comment by aaronlinv** [comment]
@j1uzhou  已经更新了一个版本，可以在 Release 中下载

**Comment by j1uzhou** [comment]
十分感谢！



---- 回复的原邮件 ----
| 发件人 | Aaron ***@***.***> |
| 日期 | 2024年03月10日 17:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [aaronlinv/JuiceTimetable] 我有一个问题 (Issue #55) |

@j1uzhou 已经更新了一个版本，可以在 Release 中下载
